### ISSUE TITLE
Live reload script hangs

### ISSUE THREAD

**Issue by fimdomeio** [jbolila/plantei.eu-website#3]
Sometime it looks like the copy from "build" to "assets" is made when build is being recreated... Script stops working and the server as to be restarted.

**Comment by jbolila** [comment]
You can try change the package.json a take the copy out of that command:

`"dev": "npm run build & npm run serve",`

because all the assets are now inside the src folder.

**Comment by fimdomeio** [comment]
It runs smoother but browser stoped auto-refreshing. I think it's because how metalsmith deletes the whole build dir. instead of updating files. I doubt if this is even fixable.
